//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAExp1.AirLine {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebXml.com.cn/", ConfigurationName="AirLine.DomesticAirlineSoap")]
    public interface DomesticAirlineSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDomesticCity", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getDomesticCity();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDomesticCity", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getDomesticCityAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDomesticAirlinesTime", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataSet getDomesticAirlinesTime(string startCity, string lastCity, string theDate, string userID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebXml.com.cn/getDomesticAirlinesTime", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataSet> getDomesticAirlinesTimeAsync(string startCity, string lastCity, string theDate, string userID);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DomesticAirlineSoapChannel : SOAExp1.AirLine.DomesticAirlineSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DomesticAirlineSoapClient : System.ServiceModel.ClientBase<SOAExp1.AirLine.DomesticAirlineSoap>, SOAExp1.AirLine.DomesticAirlineSoap {
        
        public DomesticAirlineSoapClient() {
        }
        
        public DomesticAirlineSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DomesticAirlineSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomesticAirlineSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DomesticAirlineSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataSet getDomesticCity() {
            return base.Channel.getDomesticCity();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getDomesticCityAsync() {
            return base.Channel.getDomesticCityAsync();
        }
        
        public System.Data.DataSet getDomesticAirlinesTime(string startCity, string lastCity, string theDate, string userID) {
            return base.Channel.getDomesticAirlinesTime(startCity, lastCity, theDate, userID);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> getDomesticAirlinesTimeAsync(string startCity, string lastCity, string theDate, string userID) {
            return base.Channel.getDomesticAirlinesTimeAsync(startCity, lastCity, theDate, userID);
        }
    }
}
